server:
  port: ${PORT}
spring:
  application:
    name: Artisan
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${PSQL_URL}
application:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS}
      allowed-headers: ${CORS_ALLOWED_HEADERS}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}